# Identificação do projeto — DEVE SER ÚNICO no SonarQube
sonar.projectKey=terapia-nutricional-ui
sonar.projectName=terapia-nutricional-ui
sonar.host.url=<URL_DO_SONARQUBE>
sonar.token=<SEU_TOKEN_SONAR>
sonar.plugins.downloadOnlyRequired=true

# Código fonte
sonar.sources=src/
sonar.sourceEncoding=UTF-8

# Links do projeto
sonar.links.ci=https://github.com/leobern/terapia-ocupacional-ui
sonar.links.scm=https://github.com/leobern/terapia-ocupacional-ui.git

# Cobertura de testes
sonar.javascript.lcov.reportPaths=dist/coverage/lcov.info

# Exclusões
sonar.exclusions=**/*.html,**/*.scss,**/*.css,**/*.js,**/*.mjs
sonar.coverage.exclusions=**/*.conf.js,**/*.spec.ts,**/e2e/**

# Ignore es2024 issues (remover quando Sonar suportar es2024)
sonar.issue.ignore.multicriteria=ts1
sonar.issue.ignore.multicriteria.ts1.ruleKey=javascript:S2260
sonar.issue.ignore.multicriteria.ts1.resourceKey=**/*.ts

# Versão do scanner CLI que será baixada
sonar.scanner.version=8.0.1.6346
